import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { App } from "./app";
import { AppProvider, ThemePreference } from "@/contexts/app-context";
import { cookies } from "next/headers";
import NextTopLoader from "nextjs-toploader";
import { notes } from "@/lib/data";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const cookieStore = await cookies();
	const themePreference = (cookieStore.get("themePreference")?.value ?? "system") as ThemePreference;

	return (
		<html lang="en" data-theme-preference={themePreference}>
			<head>
				<script
					dangerouslySetInnerHTML={{
						__html: `
							(function () {
								const pref = document.documentElement.dataset.themePreference;

								let theme;
								if (pref === "light" || pref === "dark") {
									theme = pref;
								} else {
									theme = window.matchMedia("(prefers-color-scheme: dark)").matches
										? "dark"
										: "light";
								}

								document.documentElement.setAttribute("data-theme", theme);
							})();
						`,
					}}
				/>
			</head>

			<body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
				<NextTopLoader />
				<AppProvider initialThemePreference={themePreference} initialData={notes}>
					<App>{children}</App>
				</AppProvider>
			</body>
		</html>
	);
}
