import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { App } from "./app";
import { AppProvider, ThemePreference } from "@/contexts/app-context";
import { cookies } from "next/headers";
import NextTopLoader from "nextjs-toploader";
import { notes } from "@/lib/data";
import { AuthProvider } from "@/contexts/auth-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const cookieStore = await cookies();
	const themePreference = (cookieStore.get("themePreference")?.value ?? "system") as ThemePreference;

	return (
		<html lang="en" data-theme="light" data-theme-preference={themePreference}>
			<head>
				<script
					dangerouslySetInnerHTML={{
						__html: `
							(function () {
								const root = document.documentElement;
								const pref = root.dataset.themePreference;

								let theme = pref;
								if (pref === "system") {
									theme = window.matchMedia("(prefers-color-scheme: dark)").matches
										? "dark"
										: "light";
								}

								root.dataset.theme = theme;
							})();
						`,
					}}
				/>
			</head>

			<body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
				<NextTopLoader />
				<AuthProvider>
					<AppProvider initialThemePreference={themePreference} initialData={notes}>
						<App>{children}</App>
					</AppProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
